ALTER TYPE "DeliveryStatus" ADD VALUE IF NOT EXISTS 'ARRIVED_AT_CUSTOMER';
ALTER TYPE "DeliveryStatus" ADD VALUE IF NOT EXISTS 'ISSUE_REPORTED';

ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "restaurantTipCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "driverTipCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "customTipCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "tipPercentage" INTEGER;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "tipType" TEXT NOT NULL DEFAULT 'NONE';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "tipStatus" TEXT NOT NULL DEFAULT 'COLLECTED';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "tipCollectedAt" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "tipCollectedByUserId" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "tipUpdatedAt" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "tipRefundedCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "trackingTokenHash" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "trackingTokenExpiresAt" TIMESTAMP(3);

UPDATE "Order"
SET
  "driverTipCents" = CASE WHEN "type" = 'DELIVERY' THEN "tipCents" ELSE 0 END,
  "restaurantTipCents" = CASE WHEN "type" = 'DELIVERY' THEN 0 ELSE "tipCents" END,
  "tipType" = CASE WHEN "tipCents" > 0 THEN 'LEGACY' ELSE 'NONE' END
WHERE "restaurantTipCents" = 0
  AND "driverTipCents" = 0
  AND "tipCents" > 0;

CREATE UNIQUE INDEX IF NOT EXISTS "Order_trackingTokenHash_key" ON "Order"("trackingTokenHash");
CREATE INDEX IF NOT EXISTS "Order_trackingTokenExpiresAt_idx" ON "Order"("trackingTokenExpiresAt");

ALTER TABLE "Delivery" ADD COLUMN IF NOT EXISTS "claimedAt" TIMESTAMP(3);
ALTER TABLE "Delivery" ADD COLUMN IF NOT EXISTS "pickedUpAt" TIMESTAMP(3);
ALTER TABLE "Delivery" ADD COLUMN IF NOT EXISTS "deliveredAt" TIMESTAMP(3);
