ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'TENANT_OWNER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'RESTAURANT_ADMIN';

CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'INVITED', 'SUSPENDED', 'DELETED');
ALTER TABLE "User" ADD COLUMN "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE';

ALTER TYPE "RestaurantStatus" ADD VALUE IF NOT EXISTS 'DELETED';
