ALTER TABLE "User"
ADD COLUMN "forcePasswordChange" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "mfaEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "mfaSetupStatus" TEXT NOT NULL DEFAULT 'NOT_CONFIGURED',
ADD COLUMN "mfaSecret" TEXT,
ADD COLUMN "mfaVerifiedAt" TIMESTAMP(3);
